add missing template when compiling a 64bit build to get some instrumentation tests to pass
Summary:
The instrumentation tests in the test plan don't build because of
    error: implicit instantiation of undefined template 'facebook::jni::detail::RefReprType<long long, void>'

full error here: P60471304

which is fixed by this diff.

Not sure if I also need to define the array template. I couldn't figure out how to do that.

Reviewed By: mhorowitz

Differential Revision: D13521761

fbshipit-source-id: 0138ff052232ff3cbcc1a4af96c8f9273120810f